### ISSUE TITLE
Error en campo "personas con pauta completa"

### ISSUE THREAD

**Issue by lucasrodes** [civio/covid-vaccination-spain#2]
Buenas,
Ante todo, gracias por tu labor! Estoy usando tus datos en mi proyecto (https://github.com/sociepy/covid19-vaccination-subnational) y son de gran utilidad!

He observado que en el commit https://github.com/civio/covid-vaccination-spain/commit/bbbaf7333858b70c4bbc85767b2684286dbb80a3, en el fichero [data.csv](data.csv) los campos `% sobre entregadas` y `personas con pauta completa` parecen estar mezclados.

**Comment by dcabo** [comment]
Hola, Lucas. Tienes toda la razón, lo rompí ayer sin darme cuenta, ya está arreglado. Gracias por avisar y ánimo con tu proyecto!
