### ISSUE TITLE
Error en línea 1159 fichero data.csv

### ISSUE THREAD

**Issue by nava17490** [civio/covid-vaccination-spain#4]
Hay un espacio en medio del nombre de Navarra en la línea 1159 del fichero data.csv.
Adjunto captura para que se vea mas claro
![image](https://user-images.githubusercontent.com/50843793/117702821-4fc84580-b1c9-11eb-9d4b-f3e984dc6ab5.png)

No es super crítico pero por si queréis limpiar mas los datos

**Comment by dcabo** [comment]
Arreglado, gracias @nava17490!
